import './js/api';
// import './js/header';
import './js/hero';
import './js/books';
// import './js/feedbacks';
import './js/events';
// import './js/article';
// import './js/location';
// import './js/footer';
import './js/modal';
